version: "2"

volumes:
  mongo:

services:
  ui:
    build:
      context: ./
      dockerfile: ./hsb-ui.Dockerfile
    depends_on:
      - mongo
    ports:
      - "80:80"

  things:
    build:
      context: ./
      dockerfile: ./hsb-things.Dockerfile
    # /sys/* is mounted in privileged mode, but only /sys/class/gpio is used, figure out more secure way
    privileged: true
    devices:
      # figure out hotplugging later, something something dbus
      - "/dev/ttyACM0:/dev/ttyACM0"
    expose:
      - "80"

  mongo:
    build:
      context: ./
      dockerfile: ./mongo.Dockerfile
    volumes:
      - mongo:/data/db
    expose:
      - "27017"
