version: "2"

volumes:
  keymaster:

services:

  gatekeeper:
    build:
      context: ./
      dockerfile: ./hsb-gatekeeper.Dockerfile
    ports:
      - "80:80"
  
  keymaster:
    build:
      context: ./
      dockerfile: ./hsb-keymaster.Dockerfile
    expose:
      - "80"
    volumes:
      - keymaster:/data

  ui:
    build:
      context: ./
      dockerfile: ./hsb-ui.Dockerfile
    expose:
      - "80"

  things:
    build:
      context: ./
      dockerfile: ./hsb-things.Dockerfile
    # /sys/* is mounted in privileged mode, but only /sys/class/gpio is used, figure out more secure way
    privileged: true
    devices:
      # figure out hotplugging later, something something dbus
      - "/dev/ttyACM0:/dev/ttyACM0"
    expose:
      - "80"
