name: Release

on:
  push:
    branches:
      - main

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: ${{secrets.BALENA_APPLICATION_NAME}}
        application-path: "./"